version: 2

sources:
  - name: healthcare_oltp
    schema: public
    tables:
      - name: patients
      - name: doctors
      - name: hospitals
      - name: insuranceproviders
      - name: medicalconditions
      - name: medications
      - name: admissions
